
[     UTC     ] Logs for dashboardapppy-birkbduyuwrxwegphddq4v.streamlit.app/
────────────────────────────────────────────────────────────────────────────────────────
[22:30:08] 🖥 Provisioning machine...
[22:30:08] 🎛 Preparing system...
[22:30:08] ⛓ Spinning up manager process...
[22:30:09] 🚀 Starting up repository: 'policy-data-insight', branch: 'main', main module: 'Dashboard_Streamlit.py'
[22:30:09] 🐙 Cloning repository...
[22:30:12] 🐙 Cloning into '/mount/src/policy-data-insight'...

[22:30:12] 🐙 Cloned repository!
[22:30:12] 🐙 Pulling code changes from Github...
[22:30:14] 📦 Processing dependencies...

──────────────────────────────────────── uv ───────────────────────────────────────────

Using uv pip install.
Using Python 3.12.10 environment at /home/adminuser/venv
error: Distribution not found at: file:///C:/b/abs_b505trsapr/croot/aiohappyeyeballs_1725434036096/work
Checking if Streamlit is installed
Installing rich for an improved exception logging
Using uv pip install.
Using Python 3.12.10 environment at /home/adminuser/venv[2025-04-20 22:30:14.418755] 
Resolved 4 packages in 124ms
Prepared 4 packages in 126ms
Installed 4 packages in 18ms
 +[2025-04-20 22:30:14.690518]  markdown-it-py==3.0.0
 + mdurl==0.1.2
 + pygments==2.19.1
 + rich==14.0.0

────────────────────────────────────────────────────────────────────────────────────────


──────────────────────────────────────── pip ───────────────────────────────────────────

Using standard pip install.
Processing /C:/b/abs_b505trsapr/croot/aiohappyeyeballs_1725434036096/work (from -r /mount/src/policy-data-insight/requirements.txt (line 1))
ERROR: Could not install packages due to an OSError: [Errno 2] No such file or directory: '/C:/b/abs_b505trsapr/croot/aiohappyeyeballs_1725434036096/work'


[notice] A new release of pip is available: 24.0 -> 25.0.1
[notice] To update, run: pip install --upgrade pip
Checking if Streamlit is installed
Installing rich for an improved exception logging
Using standard pip install.
Collecting rich>=10.14.0
  Downloading rich-14.0.0-py3-none-any.whl.metadata (18 kB)
Collecting markdown-it-py>=2.2.0 (from rich>=10.14.0)
  Downloading markdown_it_py-3.0.0-py3-none-any.whl.metadata (6.9 kB)
Collecting pygments<3.0.0,>=2.13.0 (from rich>=10.14.0)
  Downloading pygments-2.19.1-py3-none-any.whl.metadata (2.5 kB)
Collecting mdurl~=0.1 (from markdown-it-py>=2.2.0->rich>=10.14.0)
  Downloading mdurl-0.1.2-py3-none-any.whl.metadata (1.6 kB)
Downloading rich-14.0.0-py3-none-any.whl (243 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 243.2/243.2 kB 15.9 MB/s eta 0:00:00[2025-04-20 22:30:18.162977] 
Downloading markdown_it_py-3.0.0-py3-none-any.whl (87 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 87.5/87.5 kB 128.5 MB/s eta 0:00:00[2025-04-20 22:30:18.175866] 
Downloading pygments-2.19.1-py3-none-any.whl (1.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.2/1.2 MB 78.3 MB/s eta 0:00:00[2025-04-20 22:30:18.204508] 
Downloading mdurl-0.1.2-py3-none-any.whl (10.0 kB)
Installing collected packages: pygments, mdurl, markdown-it-py, rich
  Attempting uninstall: pygments
    Found existing installation: Pygments 2.19.1
    Uninstalling Pygments-2.19.1:
      Successfully uninstalled Pygments-2.19.1
  Attempting uninstall: mdurl
    Found existing installation: mdurl 0.1.2
    Uninstalling mdurl-0.1.2:
      Successfully uninstalled mdurl-0.1.2
  Attempting uninstall: markdown-it-py
    Found existing installation: markdown-it-py 3.0.0
    Uninstalling markdown-it-py-3.0.0:
      Successfully uninstalled markdown-it-py-3.0.0
  Attempting uninstall: rich
    Found existing installation: rich 14.0.0
    Uninstalling rich-14.0.0:
      Successfully uninstalled rich-14.0.0
Successfully installed markdown-it-py-3.0.0 mdurl-0.1.2 pygments-2.19.1 rich-14.0.0

[notice] A new release of pip is available: 24.0 -> 25.0.1
[notice] To update, run: pip install --upgrade pip

────────────────────────────────────────────────────────────────────────────────────────

[22:30:21] ❗️ installer returned a non-zero exit code
[22:30:21] ❗️ Error during processing dependencies! Please fix the error and push an update, or try restarting the app.